import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import path from "path";
import { copyFile, mkdir, readFile } from "fs/promises";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const deployFiles = ["main.js", "manifest.json", "styles.css"];

async function readDeployDir() {
  if (process.env.TOYBOX_DEPLOY_DIR) {
    return process.env.TOYBOX_DEPLOY_DIR;
  }

  try {
    const config = JSON.parse(await readFile(".toybox.local.json", "utf8"));
    return typeof config.deployDir === "string" && config.deployDir.trim()
      ? config.deployDir
      : null;
  } catch (error) {
    if (error?.code !== "ENOENT") {
      console.warn(`could not read .toybox.local.json: ${error.message}`);
    }
    return null;
  }
}

async function deployPluginFiles() {
  const deployDir = await readDeployDir();
  if (!deployDir) {
    return;
  }

  await mkdir(deployDir, { recursive: true });
  await Promise.all(
    deployFiles.map((file) => copyFile(file, path.join(deployDir, file))),
  );
  console.log(`deployed toybox plugin to ${deployDir}`);
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins: [
    {
      name: "toybox-deploy",
      setup(build) {
        build.onEnd(async (result) => {
          if (result.errors.length > 0) {
            return;
          }

          await deployPluginFiles();
        });
      },
    },
  ],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
