/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  VIEW_TYPE_TOYBOX_WEBVIEW: () => VIEW_TYPE_TOYBOX_WEBVIEW,
  WebView: () => WebView,
  default: () => ToyboxPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var VIEW_TYPE_TOYBOX_WEBVIEW = "toybox-webview";
var FALLBACK_URL = "about:blank";
var WebView = class extends import_obsidian.ItemView {
  constructor(leaf) {
    super(leaf);
    this.url = FALLBACK_URL;
  }
  getViewType() {
    return VIEW_TYPE_TOYBOX_WEBVIEW;
  }
  getDisplayText() {
    try {
      return new URL(this.url).hostname;
    } catch (e) {
      return "Toybox Web Viewer";
    }
  }
  getState() {
    return { url: this.url };
  }
  async setState(state, result) {
    var _a;
    this.url = (_a = normalizeHttpUrl(readUrlFromState(state))) != null ? _a : FALLBACK_URL;
    result.history = false;
    this.render();
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
    this.contentEl.empty();
  }
  render() {
    this.contentEl.empty();
    const iframe = this.contentEl.createEl("iframe");
    iframe.src = this.url;
    iframe.setAttribute(
      "sandbox",
      "allow-scripts allow-same-origin allow-forms allow-popups"
    );
    iframe.style.width = "100%";
    iframe.style.height = "100%";
    iframe.style.border = "none";
  }
};
var ToyboxPlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.registerView(VIEW_TYPE_TOYBOX_WEBVIEW, (leaf) => new WebView(leaf));
    this.registerDomEvent(
      window,
      "mousedown",
      (evt) => {
        if (evt.button !== 1) {
          return;
        }
        if (!this.getHttpUrlFromEvent(evt)) {
          return;
        }
        evt.preventDefault();
        evt.stopImmediatePropagation();
      },
      { capture: true }
    );
    this.registerDomEvent(
      window,
      "auxclick",
      (evt) => {
        if (evt.button !== 1) {
          return;
        }
        const url = this.getHttpUrlFromEvent(evt);
        if (!url) {
          return;
        }
        evt.preventDefault();
        evt.stopImmediatePropagation();
        void this.openInDefaultBrowser(url);
      },
      { capture: true }
    );
    this.registerDomEvent(
      window,
      "click",
      (evt) => {
        if (evt.button !== 0) {
          return;
        }
        if (evt.ctrlKey || evt.metaKey || evt.altKey || evt.shiftKey) {
          return;
        }
        const url = this.getHttpUrlFromEvent(evt);
        if (!url) {
          return;
        }
        evt.preventDefault();
        evt.stopImmediatePropagation();
        void this.openInObsidian(url);
      },
      { capture: true }
    );
  }
  async onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_TOYBOX_WEBVIEW);
  }
  getHttpUrlFromEvent(evt) {
    var _a;
    const anchor = this.findAnchor(evt);
    return normalizeHttpUrl((_a = anchor == null ? void 0 : anchor.href) != null ? _a : anchor == null ? void 0 : anchor.getAttribute("href"));
  }
  findAnchor(evt) {
    if (evt.target instanceof Element) {
      const anchor = evt.target.closest("a[href]");
      if (anchor instanceof HTMLAnchorElement) {
        return anchor;
      }
    }
    for (const node of evt.composedPath()) {
      if (node instanceof HTMLAnchorElement && node.href) {
        return node;
      }
      if (node instanceof Element) {
        const anchor = node.closest("a[href]");
        if (anchor instanceof HTMLAnchorElement) {
          return anchor;
        }
      }
    }
    return null;
  }
  async openInObsidian(url) {
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.setViewState({
      type: VIEW_TYPE_TOYBOX_WEBVIEW,
      active: true,
      state: { url }
    });
    await this.app.workspace.revealLeaf(leaf);
  }
  async openInDefaultBrowser(url) {
    const shell = this.getElectronShell();
    if (shell) {
      await shell.openExternal(url);
      return;
    }
    window.open(url, "_blank", "noopener");
  }
  getElectronShell() {
    var _a;
    if (!import_obsidian.Platform.isDesktopApp) {
      return null;
    }
    try {
      const electron = require("electron");
      return (_a = electron.shell) != null ? _a : null;
    } catch (e) {
      return null;
    }
  }
};
function normalizeHttpUrl(url) {
  if (!url) {
    return null;
  }
  try {
    const parsedUrl = new URL(url);
    if (parsedUrl.protocol !== "http:" && parsedUrl.protocol !== "https:") {
      return null;
    }
    return parsedUrl.toString();
  } catch (e) {
    return null;
  }
}
function readUrlFromState(state) {
  if (!state || typeof state !== "object") {
    return null;
  }
  const maybeUrl = state.url;
  return typeof maybeUrl === "string" ? maybeUrl : null;
}
